project:
  type: book
  output-dir: docs
  render:
    - index.qmd
    - "notebooks/*.ipynb"
    - "slides/*.qmd"

book:
  title: "BASC0005"
  subtitle: "Quantitative Methods 2: Data Science and Visualisation"
  author: "Ollie Ballinger"
  google-analytics: UA-154866877-2
  chapters:
    - index.qmd
    - part: "Week 1 · Introduction"
      chapters:
        - href: "./notebooks/W01. Python Recap.ipynb"
          text: "Workshop: Python Recap"
    - part: "Week 2 · Data"
      chapters:
        - href: slides/w02.qmd
          text: "Lecture slides"
        - href: "./notebooks/W02. Pandas.ipynb"
          text: "Workshop: Pandas"
    - part: "Week 3 · Spatial & Networks"
      chapters:
        - href: slides/w03.qmd
          text: "Lecture slides"
        - href: "./notebooks/W03. Spatial Data.ipynb"
          text: "Workshop: Spatial Data"
    - part: "Week 4 · Text as Data"
      chapters:
        - href: slides/w04.qmd
          text: "Lecture slides"
        - href: "./notebooks/W04. Natural Language Processing.ipynb"
          text: "Workshop: Natural Language Processing"
    - part: "Week 5 · Sampling"
      chapters:
        - href: "./notebooks/W05. Distributions and Basic Statistics.ipynb"
          text: "Workshop: Distributions"
    - part: "Reading Week"
      chapters:
        - href: "./notebooks/RW. Merging and Joining.ipynb"
          text: "Workshop: Merging and Joining"
    - part: "Week 6 · Hypothesis Testing"
      chapters:
        - href: slides/w06.qmd
          text: "Lecture slides"
        - href: "./notebooks/W06. Hypothesis Testing.ipynb"
          text: "Workshop: Hypothesis Testing"
    - part: "Week 7 · Regression"
      chapters:
        - href: slides/w07.qmd
          text: "Lecture slides"
        - href: "./notebooks/W07. Linear Regression.ipynb"
          text: "Workshop: Linear Regression"
    - part: "Week 8 · Causal Inference"
      chapters:
        - href: slides/w08.qmd
          text: "Lecture slides"
        - href: "./notebooks/W08. Diff-in-Diff.ipynb"
          text: "Workshop: Diff-in-Diff"
        - href: "./notebooks/W09. Regression Discontinuity.ipynb"
          text: "Workshop: Regression Discontinuity"
    - part: "Week 9 · Prediction"
      chapters:
        - href: slides/w09.qmd
          text: "Lecture slides"
        - href: "./notebooks/W10. Machine Learning.ipynb"
          text: "Workshop: Machine Learning"
    - part: "Week 10 · Clustering"
      chapters:
        - href: slides/w10.qmd
          text: "Lecture slides"

  repo-url: https://github.com/oballinger/BASC0005/
  repo-actions: [edit]
  sidebar:
    logo: logo2.png
    collapse-level: 1
bibliography: references.bib

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    number-sections: false
    toc-title: "On this page"



